USE govexam;

-- ── Roles ─────────────────────────────────────────────────────────────────────
INSERT IGNORE INTO roles (id, name) VALUES (1,'admin'),(2,'student');

-- ── Default users (passwords: Admin@123 / Student@123) ───────────────────────
-- bcrypt hash of Admin@123
INSERT IGNORE INTO users (id,name,email,password_hash,role_id,is_active,email_verified)
VALUES
('00000000-0000-0000-0000-000000000001','Admin User','admin@govexam.in',
 '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/HS.iK2i',1,TRUE,TRUE),
('00000000-0000-0000-0000-000000000002','Demo Student','student@govexam.in',
 '$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uRrpg/ZV6',2,TRUE,TRUE);

-- ── Topics ────────────────────────────────────────────────────────────────────
INSERT IGNORE INTO topics (id,name,slug,source) VALUES
(1,'Familiarity with Personal Computer Specs','pc-specs','Railway AME Group B IT'),
(2,'Basic Local Area Networks: Servers, Hubs, Switches','lan-basics','Railway AME Group B IT'),
(3,'Structured Cabling, Nodes, Network Applications','structured-cabling','Railway AME Group B IT'),
(4,'Using Internet: Email, Browsing, Searching','internet-usage','Railway AME Group B IT'),
(5,'General awareness of Indian Railways digital platforms','railway-digital','Railway AME Group B IT');

-- ── Questions: PC Specs (1-20) ────────────────────────────────────────────────
INSERT IGNORE INTO questions (id,topic_id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,difficulty_level,source,status) VALUES
(1,1,'The CPU of a computer primarily performs which function?','Stores data permanently','Processes instructions','Displays graphics','Controls printer output','Processes instructions','CPU executes program instructions and performs calculations.',0,'Railway AME Group B IT','active'),
(2,1,'Which component is considered volatile memory?','Hard Disk','SSD','RAM','CD-ROM','RAM','RAM loses data when power is switched off.',0,'Railway AME Group B IT','active'),
(3,1,'Which of the following is a secondary storage device?','RAM','Processor','Cache','Hard Disk','Hard Disk','Hard disk stores data permanently.',0,'Railway AME Group B IT','active'),
(4,1,'The speed of a processor is generally measured in:','Bytes','Hertz','Bits','Pixels','Hertz','Processor speed is measured in MHz or GHz.',0,'Railway AME Group B IT','active'),
(5,1,'Which device is used to read Compact Discs?','Floppy Drive','CD-ROM Drive','Hard Disk','Pen Drive','CD-ROM Drive','CD-ROM drive reads data from compact discs.',0,'Railway AME Group B IT','active'),
(6,1,'Cache memory is mainly used to:','Increase storage capacity','Improve processing speed','Display images','Store backup data','Improve processing speed','Cache memory speeds up CPU performance.',0,'Railway AME Group B IT','active'),
(7,1,'Which of the following storage devices has the least capacity?','Hard Disk','DVD','Floppy Disk','SSD','Floppy Disk','Floppy disks typically store 1.44 MB.',0,'Railway AME Group B IT','active'),
(8,1,'Multimedia refers to the integration of:','Text only','Audio only','Video only','Text, Audio, Video and Graphics','Text, Audio, Video and Graphics','Multimedia combines multiple forms of media.',0,'Railway AME Group B IT','active'),
(9,1,'Which unit is used to measure RAM capacity?','Hertz','Byte','Volt','Watt','Byte','RAM capacity is measured in MB or GB.',0,'Railway AME Group B IT','active'),
(10,1,'SSD differs from HDD mainly because it:','Uses magnetic storage','Has moving parts','Uses flash memory','Needs floppy drive','Uses flash memory','SSD uses flash memory and has no moving parts.',0,'Railway AME Group B IT','active'),
(11,1,'Which factor directly affects CPU performance the most?','Monitor size','Clock speed and number of cores','Keyboard type','Printer resolution','Clock speed and number of cores','CPU performance depends mainly on clock speed (GHz) and number of cores.',1,'Railway AME Group B IT','active'),
(12,1,'Which memory is fastest in access time?','RAM','Hard Disk','Cache Memory','DVD','Cache Memory','Cache memory is closest to CPU and has the fastest access time.',1,'Railway AME Group B IT','active'),
(13,1,'The main difference between SRAM and DRAM is that SRAM:','Is slower than DRAM','Requires refreshing','Does not require refreshing','Is used as hard disk memory','Does not require refreshing','SRAM does not require refreshing, unlike DRAM.',1,'Railway AME Group B IT','active'),
(14,1,'Which interface standard is commonly used for modern internal hard drives?','IDE','SATA','VGA','PS/2','SATA','SATA is widely used for connecting HDDs and SSDs.',1,'Railway AME Group B IT','active'),
(15,1,'What is the typical RPM of a high-performance HDD?','360 RPM','720 RPM','7200 RPM','72 RPM','7200 RPM','Most high-performance HDDs operate at 7200 RPM or higher.',1,'Railway AME Group B IT','active'),
(16,1,'Which of the following affects the data transfer rate of RAM?','RAM frequency and bus width','Monitor resolution','Mouse DPI','Speaker wattage','RAM frequency and bus width','RAM speed depends on frequency (MHz) and bus width.',1,'Railway AME Group B IT','active'),
(17,1,'Which technology allows a single CPU core to handle multiple threads?','Hyper-Threading','Overclocking','Virtual Memory','Disk Fragmentation','Hyper-Threading','Hyper-Threading allows a core to execute multiple threads simultaneously.',1,'Railway AME Group B IT','active'),
(18,1,'What is the primary function of the BIOS/UEFI?','Store user files','Control printer operations','Initialize hardware during booting','Increase RAM capacity','Initialize hardware during booting','BIOS/UEFI initializes hardware before the OS loads.',1,'Railway AME Group B IT','active'),
(19,1,'Which storage device has the lowest latency?','HDD','Floppy Disk','SSD','DVD','SSD','SSD has very low latency due to absence of moving parts.',1,'Railway AME Group B IT','active'),
(20,1,'Virtual memory in a computer system is primarily implemented using:','Cache memory','ROM','Hard disk space','Processor registers','Hard disk space','Virtual memory uses hard disk space to extend RAM logically.',1,'Railway AME Group B IT','active');

-- ── Questions: LAN Basics (61-100) ───────────────────────────────────────────
INSERT IGNORE INTO questions (id,topic_id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,difficulty_level,source,status) VALUES
(61,2,'LAN stands for:','Large Area Network','Local Area Network','Long Area Network','Limited Area Network','Local Area Network','LAN connects computers within a small geographical area.',0,'Railway AME Group B IT','active'),
(62,2,'Which device connects multiple computers in a LAN?','Printer','Hub','Scanner','Monitor','Hub','Hub connects multiple devices in a network.',0,'Railway AME Group B IT','active'),
(63,2,'A server in a network is mainly used to:','Play games','Provide services to clients','Print documents only','Control keyboard','Provide services to clients','Server provides resources and services.',0,'Railway AME Group B IT','active'),
(64,2,'Which device forwards data only to the intended recipient?','Hub','Switch','Repeater','Modem','Switch','Switch uses MAC address to forward data.',0,'Railway AME Group B IT','active'),
(65,2,'Hub works at which OSI layer?','Network Layer','Transport Layer','Physical Layer','Application Layer','Physical Layer','Hub operates at Physical Layer (Layer 1).',0,'Railway AME Group B IT','active'),
(66,2,'Switch works at which OSI layer?','Physical Layer','Data Link Layer','Application Layer','Session Layer','Data Link Layer','Switch operates at Layer 2.',0,'Railway AME Group B IT','active'),
(67,2,'Which device broadcasts data to all connected devices?','Switch','Router','Hub','Server','Hub','Hub sends data to all ports.',0,'Railway AME Group B IT','active'),
(68,2,'The main advantage of a switch over a hub is:','Lower cost','Better security and reduced collisions','Less ports','No power required','Better security and reduced collisions','Switch reduces collisions.',0,'Railway AME Group B IT','active'),
(69,2,'Which of the following is an example of a network server?','File Server','Keyboard','Mouse','Scanner','File Server','File server stores and manages files.',0,'Railway AME Group B IT','active'),
(70,2,'In LAN, computers are usually connected using:','Telephone line','Fiber cable only','Ethernet cable','TV cable','Ethernet cable','Ethernet cables are common in LAN.',0,'Railway AME Group B IT','active'),
(71,2,'Which device stores and manages shared files?','Switch','Server','Hub','Router','Server','Server manages shared resources.',0,'Railway AME Group B IT','active'),
(72,2,'A hub typically has how many collision domains?','One','Multiple','Zero','Unlimited','One','All devices share same collision domain in hub.',0,'Railway AME Group B IT','active'),
(73,2,'A switch creates how many collision domains?','One','One per port','None','Two only','One per port','Each switch port is separate collision domain.',0,'Railway AME Group B IT','active'),
(74,2,'Which address does a switch use to forward frames?','IP address','MAC address','Port number','URL','MAC address','Switch forwards using MAC address table.',0,'Railway AME Group B IT','active'),
(75,2,'Which of the following is NOT a networking device?','Hub','Switch','Server','Printer','Printer','Printer is peripheral device.',0,'Railway AME Group B IT','active'),
(76,2,'Which topology is commonly used in LAN with switches?','Star topology','Ring topology','Bus topology','Mesh only','Star topology','Switch-based LAN usually uses star topology.',0,'Railway AME Group B IT','active'),
(77,2,'Which device connects different networks together?','Hub','Switch','Router','Server','Router','Router connects multiple networks.',0,'Railway AME Group B IT','active'),
(78,2,'Which LAN device increases the number of ports?','Hub','Scanner','Monitor','Keyboard','Hub','Hub provides multiple connection ports.',0,'Railway AME Group B IT','active'),
(79,2,'Which server manages user authentication in a network?','Web Server','File Server','Authentication Server','Print Server','Authentication Server','Authentication server verifies users.',0,'Railway AME Group B IT','active'),
(80,2,'LAN typically covers:','Entire country','Entire world','Small geographic area','Multiple continents','Small geographic area','LAN covers limited area like office or building.',0,'Railway AME Group B IT','active'),
(81,2,'In a switched LAN, how does a switch learn MAC addresses?','Using ARP requests only','By reading IP packets','By examining source MAC of incoming frames','Manually configured only','By examining source MAC of incoming frames','Switch builds MAC table from source addresses.',1,'Railway AME Group B IT','active'),
(82,2,'What happens when a switch receives a frame with unknown destination MAC?','It drops the frame','It sends to router','It floods to all ports except source','It blocks the port','It floods to all ports except source','Unknown unicast is flooded.',1,'Railway AME Group B IT','active'),
(83,2,'Which device separates broadcast domains?','Hub','Switch','Router','Repeater','Router','Router breaks broadcast domains.',1,'Railway AME Group B IT','active'),
(84,2,'In a LAN using hubs, collision handling is managed by:','Switching protocol','CSMA/CD','DHCP','DNS','CSMA/CD','Hubs rely on CSMA/CD for collision detection.',1,'Railway AME Group B IT','active'),
(85,2,'Which switching method checks frame for errors before forwarding?','Cut-through switching','Fragment-free switching','Store-and-forward switching','Adaptive switching','Store-and-forward switching','Store-and-forward verifies CRC.',1,'Railway AME Group B IT','active'),
(86,2,'Which topology can create broadcast storms if no loop prevention is enabled?','Star','Bus','Ring','Redundant switched network','Redundant switched network','Switch loops cause broadcast storm.',1,'Railway AME Group B IT','active'),
(87,2,'Which protocol prevents switching loops in LAN?','ARP','RIP','STP','HTTP','STP','Spanning Tree Protocol prevents loops.',1,'Railway AME Group B IT','active'),
(88,2,'In a fully switched network, collision domains are:','One per network','One per port','None','Unlimited shared','One per port','Each switch port is separate collision domain.',1,'Railway AME Group B IT','active'),
(89,2,'Which server provides automatic IP address assignment?','File Server','DNS Server','DHCP Server','Web Server','DHCP Server','DHCP dynamically assigns IP addresses.',1,'Railway AME Group B IT','active'),
(90,2,'Which address type is used for frame delivery within a LAN?','IP Address','MAC Address','Port Address','URL','MAC Address','LAN frame delivery uses MAC address.',1,'Railway AME Group B IT','active'),
(91,2,'Which type of server stores web pages and delivers them to clients?','File Server','Print Server','Web Server','Authentication Server','Web Server','Web server handles HTTP requests.',1,'Railway AME Group B IT','active'),
(92,2,'What is the maximum segment length for standard Ethernet over UTP?','10 meters','50 meters','100 meters','500 meters','100 meters','UTP Ethernet max distance is 100m.',1,'Railway AME Group B IT','active'),
(93,2,'Which OSI layer is responsible for MAC addressing?','Network Layer','Data Link Layer','Physical Layer','Transport Layer','Data Link Layer','MAC is part of Layer 2.',1,'Railway AME Group B IT','active'),
(94,2,'Which device operates in full-duplex mode eliminating collisions?','Hub','Switch','Repeater','Bridge (half-duplex only)','Switch','Switch supports full-duplex.',1,'Railway AME Group B IT','active'),
(95,2,'Which VLAN feature improves security in LAN?','Shared broadcast','Network segmentation','Increased collisions','Physical rewiring','Network segmentation','VLAN isolates traffic logically.',1,'Railway AME Group B IT','active'),
(96,2,'Which server translates domain names into IP addresses?','DHCP Server','DNS Server','Mail Server','FTP Server','DNS Server','DNS resolves domain names.',1,'Railway AME Group B IT','active'),
(97,2,'Which cable is commonly used in modern LAN installations?','Coaxial cable only','UTP cable','Telephone cable','Power cable','UTP cable','UTP Cat5e/Cat6 is common.',0,'Railway AME Group B IT','active'),
(98,2,'Which command helps verify connectivity between two LAN devices?','ipconfig','ping','dir','copy','ping','Ping tests reachability.',0,'Railway AME Group B IT','active'),
(99,2,'Which term describes logical grouping of devices within a switch?','Subnet','VLAN','Gateway','Proxy','VLAN','VLAN segments switch logically.',1,'Railway AME Group B IT','active'),
(100,2,'Which factor mainly determines LAN performance?','Monitor resolution','Bandwidth and latency','Keyboard type','Printer speed','Bandwidth and latency','LAN performance depends on bandwidth & delay.',1,'Railway AME Group B IT','active');

-- ── Questions: Structured Cabling (101-120) ───────────────────────────────────
INSERT IGNORE INTO questions (id,topic_id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,difficulty_level,source,status) VALUES
(101,3,'Structured cabling is mainly used for:','Power supply wiring','Network connectivity','Water supply lines','Air conditioning','Network connectivity','Structured cabling provides standardized network wiring.',0,'Railway AME Group B IT','active'),
(102,3,'A node in a network refers to:','Only server','Only switch','Any connected device','Only router','Any connected device','Node is any device connected to network.',0,'Railway AME Group B IT','active'),
(103,3,'Which cable is commonly used in structured LAN cabling?','HDMI','USB','UTP cable','Power cable','UTP cable','UTP cables like Cat6 are common.',0,'Railway AME Group B IT','active'),
(104,3,'RJ-45 connector is used for:','Telephone line only','Fiber optics only','Ethernet networking','Power supply','Ethernet networking','RJ-45 is standard Ethernet connector.',0,'Railway AME Group B IT','active'),
(105,3,'Patch panel is used in structured cabling to:','Store data','Organize cable connections','Increase bandwidth','Power network devices','Organize cable connections','Patch panels manage cables neatly.',0,'Railway AME Group B IT','active'),
(106,3,'Which category cable supports Gigabit Ethernet?','Cat3','Cat5e','Cat1','Coaxial only','Cat5e','Cat5e and above support Gigabit.',0,'Railway AME Group B IT','active'),
(107,3,'Which device is considered a network node?','Computer','Printer','Server','All of the above','All of the above','All connected devices are nodes.',0,'Railway AME Group B IT','active'),
(108,3,'Which application is used for sending emails over a network?','FTP','SMTP','HTTP','Telnet','SMTP','SMTP is used for sending emails.',0,'Railway AME Group B IT','active'),
(109,3,'Which network application is used to transfer files?','HTTP','FTP','POP3','SNMP','FTP','FTP is File Transfer Protocol.',0,'Railway AME Group B IT','active'),
(110,3,'Horizontal cabling connects:','Building to ISP','Workstation to telecom room','Country to country','Router to internet only','Workstation to telecom room','Horizontal cabling runs from telecom room to outlets.',1,'Railway AME Group B IT','active'),
(111,3,'Backbone cabling connects:','Two countries','Telecom rooms within building','Printer to PC','Keyboard to CPU','Telecom rooms within building','Backbone connects floors or buildings.',1,'Railway AME Group B IT','active'),
(112,3,'Which protocol is used for web browsing?','FTP','HTTP','SMTP','POP3','HTTP','HTTP loads web pages.',0,'Railway AME Group B IT','active'),
(113,3,'Fiber optic cable transmits data using:','Electric signals','Light signals','Sound waves','Magnetic waves','Light signals','Fiber uses light pulses.',0,'Railway AME Group B IT','active'),
(114,3,'Which tool is used to test LAN cable connectivity?','Multimeter','Cable tester','Voltmeter','Oscilloscope','Cable tester','Cable tester checks wiring continuity.',0,'Railway AME Group B IT','active'),
(115,3,'Which layer of structured cabling includes patch cords?','Work area','Entrance facility','Backbone','ISP layer','Work area','Patch cords are used at work area.',1,'Railway AME Group B IT','active'),
(116,3,'Which network application is used for remote login?','HTTP','FTP','Telnet','SMTP','Telnet','Telnet enables remote login.',0,'Railway AME Group B IT','active'),
(117,3,'In networking, NIC stands for:','Network Internal Cable','Network Interface Card','Node Internet Control','Network Input Circuit','Network Interface Card','NIC connects device to network.',0,'Railway AME Group B IT','active'),
(118,3,'Which structured cabling standard is commonly followed?','TIA/EIA','ISO 9001','IEEE 802.11 only','HTTP','TIA/EIA','TIA/EIA defines cabling standards.',1,'Railway AME Group B IT','active'),
(119,3,'Which node acts as central resource provider?','Client','Server','Hub','Repeater','Server','Server provides services.',0,'Railway AME Group B IT','active'),
(120,3,'Which application protocol retrieves emails from server?','SMTP','POP3','FTP','HTTP','POP3','POP3 retrieves emails.',0,'Railway AME Group B IT','active');

-- ── Questions: Internet Usage (121-140) ───────────────────────────────────────
INSERT IGNORE INTO questions (id,topic_id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,difficulty_level,source,status) VALUES
(121,4,'Which protocol is primarily used for sending emails?','POP3','SMTP','HTTP','FTP','SMTP','SMTP is used to send emails.',0,'Railway AME Group B IT','active'),
(122,4,'Which protocol is used to receive emails from a mail server?','SMTP','HTTP','POP3','DNS','POP3','POP3 retrieves emails from server.',0,'Railway AME Group B IT','active'),
(123,4,'IMAP differs from POP3 because IMAP:','Deletes mail from server automatically','Stores emails only locally','Synchronizes emails across devices','Cannot download attachments','Synchronizes emails across devices','IMAP keeps mail synced on multiple devices.',1,'Railway AME Group B IT','active'),
(124,4,'Which part of an email address identifies the mail server?','Username','@ symbol','Domain name','Password','Domain name','The domain after @ identifies server.',0,'Railway AME Group B IT','active'),
(125,4,'HTTPS differs from HTTP because it:','Is faster','Uses encryption','Uses UDP','Cannot display images','Uses encryption','HTTPS uses SSL/TLS encryption.',0,'Railway AME Group B IT','active'),
(126,4,'Which search operator is used to find an exact phrase in Google?','* (asterisk)','\" \" (quotation marks)','- (minus)','OR','\" \" (quotation marks)','Quotes search exact phrase.',0,'Railway AME Group B IT','active'),
(127,4,'Which search operator excludes a word from search results?','AND','+','-','*','-','Minus excludes unwanted terms.',0,'Railway AME Group B IT','active'),
(128,4,'Which component translates domain names into IP addresses?','HTTP','FTP','DNS','SMTP','DNS','DNS resolves domain names.',0,'Railway AME Group B IT','active'),
(129,4,'Which is an example of a web browser?','Google','Chrome','Yahoo','Gmail','Chrome','Chrome is a browser application.',0,'Railway AME Group B IT','active'),
(130,4,'Cookies stored by a browser are mainly used to:','Increase internet speed','Store user session information','Block viruses','Encrypt emails','Store user session information','Cookies remember login/session data.',0,'Railway AME Group B IT','active'),
(131,4,'Phishing emails are designed to:','Increase bandwidth','Steal sensitive information','Improve browsing speed','Encrypt attachments','Steal sensitive information','Phishing attempts to steal data.',0,'Railway AME Group B IT','active'),
(132,4,'Which protocol is commonly used to securely access webmail?','HTTP','HTTPS','FTP','Telnet','HTTPS','Secure browsing uses HTTPS.',0,'Railway AME Group B IT','active'),
(133,4,'Which command can refine search results to a specific website?','site:','find:','web:','url:','site:','site:example.com limits search.',1,'Railway AME Group B IT','active'),
(134,4,'Which of the following is a secure email protocol?','SMTP over SSL/TLS','FTP','HTTP','ARP','SMTP over SSL/TLS','Secure SMTP uses SSL/TLS.',1,'Railway AME Group B IT','active'),
(135,4,'Which search engine is developed by Microsoft?','Google','Bing','Yahoo','DuckDuckGo','Bing','Bing is Microsoft search engine.',0,'Railway AME Group B IT','active'),
(136,4,'Which header field in email specifies the recipient?','From','To','CC','Subject','To','To field indicates main recipient.',0,'Railway AME Group B IT','active'),
(137,4,'Which technology ensures secure data transmission over internet?','SSL/TLS','HTML','SMTP','ARP','SSL/TLS','SSL/TLS encrypts data.',0,'Railway AME Group B IT','active'),
(138,4,'Which of the following improves search relevance?','Using long random text','Using specific keywords','Typing full paragraph','Using only symbols','Using specific keywords','Specific keywords give better results.',0,'Railway AME Group B IT','active'),
(139,4,'What does URL stand for?','Universal Resource Locator','Uniform Resource Locator','Unique Reference Link','Unified Resource Link','Uniform Resource Locator','URL is web address.',0,'Railway AME Group B IT','active'),
(140,4,'Which technique helps verify authenticity of a website?','Checking HTTP only','Ignoring padlock symbol','Checking SSL certificate details','Disabling antivirus','Checking SSL certificate details','Valid certificate ensures secure site.',1,'Railway AME Group B IT','active');

-- ── Questions: Railway Digital Platforms (141-200) ────────────────────────────
INSERT IGNORE INTO questions (id,topic_id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,difficulty_level,source,status) VALUES
(141,5,'e-Office system in Indian Railways is mainly used for:','Train operations','Digital file movement and office work','Ticket booking','Freight loading','Digital file movement and office work','e-Office enables paperless file processing.',0,'Railway AME Group B IT','active'),
(142,5,'HRMS in Indian Railways stands for:','Human Resource Management System','High Revenue Monitoring System','Head Railway Monitoring System','Human Railway Mail Service','Human Resource Management System','HRMS manages employee records digitally.',0,'Railway AME Group B IT','active'),
(143,5,'IPAS is primarily related to:','Payroll and accounting','Signal operations','Passenger reservation','Track maintenance','Payroll and accounting','IPAS handles finance and salary processing.',0,'Railway AME Group B IT','active'),
(144,5,'SPARROW system is used for:','Online ticket booking','Performance appraisal reporting','Inventory management','Railway recruitment','Performance appraisal reporting','SPARROW manages APAR online.',0,'Railway AME Group B IT','active'),
(145,5,'LIMBS portal is related to:','Legal case monitoring','Material procurement','Employee leave','Medical records','Legal case monitoring','LIMBS tracks court cases.',0,'Railway AME Group B IT','active'),
(146,5,'ARPAN portal is mainly used for:','Confidential report processing','Passenger complaints','Procurement','Freight billing','Confidential report processing','ARPAN digitizes confidential records.',0,'Railway AME Group B IT','active'),
(147,5,'CPGRAMS is used for:','Public grievance redressal','Salary processing','Inventory control','Train scheduling','Public grievance redressal','CPGRAMS handles citizen grievances.',0,'Railway AME Group B IT','active'),
(148,5,'ANUBHAV portal is related to:','Retired employee experience sharing','Freight billing','Ticket booking','Vendor registration','Retired employee experience sharing','ANUBHAV records retirees contributions.',0,'Railway AME Group B IT','active'),
(149,5,'UMID card in Railways is associated with:','Medical services','Freight operations','Procurement','Ticket checking','Medical services','UMID provides medical identity.',0,'Railway AME Group B IT','active'),
(150,5,'RESS stands for:','Railway Employee Self Service','Railway Electronic Safety System','Railway Emergency Signal Service','Railway Equipment Storage System','Railway Employee Self Service','RESS allows employees to view salary slips.',0,'Railway AME Group B IT','active'),
(151,5,'GeM portal is used for:','Government e-Marketplace procurement','Ticket booking','Freight operations','Train control','Government e-Marketplace procurement','GeM enables online government purchases.',0,'Railway AME Group B IT','active'),
(152,5,'UDM in Railways is related to:','Materials management','Passenger reservation','Recruitment','Signal inspection','Materials management','UDM stands for Unified Depot Management.',0,'Railway AME Group B IT','active'),
(153,5,'IREPS portal is mainly used for:','E-procurement and tenders','Leave approval','Ticket booking','Freight tracking','E-procurement and tenders','IREPS handles railway tenders.',0,'Railway AME Group B IT','active'),
(154,5,'FMM system is related to:','Financial and material management','Freight movement monitoring','Passenger feedback','Medical records','Financial and material management','FMM integrates finance and materials.',1,'Railway AME Group B IT','active'),
(155,5,'HR-MIS is used to:','Manage employee information','Control train speed','Monitor signals','Book tickets','Manage employee information','HR-MIS stores personnel data.',0,'Railway AME Group B IT','active'),
(156,5,'Digital signature in e-Office is used for:','Authenticating documents','Speeding trains','Reducing freight','Ticket cancellation','Authenticating documents','Digital signature validates file approvals.',0,'Railway AME Group B IT','active'),
(157,5,'IPAS helps in generation of:','Salary slips','Train charts','Passenger tickets','Signal diagrams','Salary slips','IPAS generates pay bills.',0,'Railway AME Group B IT','active'),
(158,5,'SPARROW is associated with:','APAR management','Procurement','Freight billing','Recruitment exams','APAR management','SPARROW digitizes performance reports.',0,'Railway AME Group B IT','active'),
(159,5,'CPGRAMS is accessible to:','Citizens and employees','Only vendors','Only ministers','Only contractors','Citizens and employees','Public can lodge grievances online.',0,'Railway AME Group B IT','active'),
(160,5,'IREPS is mainly used by:','Vendors and Railway procurement officials','Passengers','Ticket examiners','Drivers','Vendors and Railway procurement officials','IREPS handles online tenders.',0,'Railway AME Group B IT','active'),
(161,5,'GeM ensures:','Transparent procurement','Train punctuality','Signal safety','Passenger comfort','Transparent procurement','GeM promotes transparency.',0,'Railway AME Group B IT','active'),
(162,5,'UMID card benefits railway employees in:','Medical treatment','Ticket booking','Freight booking','Track inspection','Medical treatment','UMID integrates medical data.',0,'Railway AME Group B IT','active'),
(163,5,'HRMS portal allows employees to apply for:','Leave online','Train ticket','Freight contract','Signal clearance','Leave online','Leave module is available in HRMS.',0,'Railway AME Group B IT','active'),
(164,5,'LIMBS monitors:','Legal cases','Passenger reservations','Train schedules','Fuel consumption','Legal cases','LIMBS tracks court matters.',0,'Railway AME Group B IT','active'),
(165,5,'ANUBHAV portal records:','Retired employees experiences','Vendor bids','Train timings','Signal data','Retired employees experiences','ANUBHAV documents service contributions.',0,'Railway AME Group B IT','active'),
(166,5,'UDM integrates:','Depot inventory functions','Passenger ticketing','Freight tracking','Medical services','Depot inventory functions','UDM manages depot materials.',1,'Railway AME Group B IT','active'),
(167,5,'FMM improves:','Financial transparency','Train speed','Signal voltage','Passenger comfort','Financial transparency','FMM integrates finance modules.',1,'Railway AME Group B IT','active'),
(168,5,'RESS portal allows employees to:','View salary and PF details','Book tickets','Apply tender','Track trains','View salary and PF details','RESS provides payroll access.',0,'Railway AME Group B IT','active'),
(169,5,'e-Office reduces:','Paperwork','Train speed','Freight charges','Fuel consumption','Paperwork','e-Office supports paperless workflow.',0,'Railway AME Group B IT','active'),
(170,5,'Digital platforms in Railways mainly promote:','Efficiency and transparency','Manual paperwork','Ticket black marketing','Delay in processing','Efficiency and transparency','Digitalization improves governance.',0,'Railway AME Group B IT','active'),
(171,5,'Which module in HRMS allows employees to update their personal details online?','e-Pass module','Employee Self Service (ESS)','Payroll module','SPARROW module','Employee Self Service (ESS)','ESS in HRMS enables self-service updates.',1,'Railway AME Group B IT','active'),
(172,5,'IPAS integrates with which system for budget and expenditure control?','UDM','FMM','CPGRAMS','ANUBHAV','FMM','FMM integrates finance and material accounting.',1,'Railway AME Group B IT','active'),
(173,5,'SPARROW primarily digitizes which document?','Service Book','APAR','Leave Application','Tender Notice','APAR','SPARROW handles online APAR workflow.',1,'Railway AME Group B IT','active'),
(174,5,'IREPS ensures transparency by providing:','Manual tender submission','Online bid submission and tracking','Offline vendor meetings','Paper-based contracts','Online bid submission and tracking','IREPS supports end-to-end e-tendering.',1,'Railway AME Group B IT','active'),
(175,5,'GeM differs from IREPS because GeM is:','Railway-specific only','Government-wide procurement portal','Only for finance','Only for legal cases','Government-wide procurement portal','GeM serves all government departments.',1,'Railway AME Group B IT','active'),
(176,5,'Which platform allows digital movement and approval of files with DSC?','CPGRAMS','e-Office','RESS','UDM','e-Office','e-Office supports digital signatures.',1,'Railway AME Group B IT','active'),
(177,5,'UMID card integrates with which system for medical records?','IPAS','HRMS','Railway Health Management System','IREPS','Railway Health Management System','UMID centralizes medical data digitally.',1,'Railway AME Group B IT','active'),
(178,5,'LIMBS portal helps railway administration in:','Tracking court case status','Salary generation','Tender evaluation','Freight billing','Tracking court case status','LIMBS monitors legal matters.',1,'Railway AME Group B IT','active'),
(179,5,'CPGRAMS grievances are monitored at which level?','Only Railway Board','Divisional level only','Multiple administrative levels','Vendor level','Multiple administrative levels','Grievances can be tracked across levels.',1,'Railway AME Group B IT','active'),
(180,5,'UDM primarily supports which function?','Unified Depot inventory management','Ticket reservation','Legal documentation','Medical insurance','Unified Depot inventory management','UDM digitizes depot stock handling.',1,'Railway AME Group B IT','active'),
(181,5,'FMM improves financial reporting by:','Manual ledger maintenance','Real-time accounting integration','Paper file system','Telephone approvals','Real-time accounting integration','FMM ensures integrated accounting.',1,'Railway AME Group B IT','active'),
(182,5,'Which portal is specifically used for Railway e-procurement?','GeM','IREPS','CPGRAMS','RESS','IREPS','IREPS is railway e-tender portal.',1,'Railway AME Group B IT','active'),
(183,5,'HRMS helps management in:','Monitoring workforce data','Train scheduling','Signal operations','Freight billing','Monitoring workforce data','HRMS stores personnel data centrally.',1,'Railway AME Group B IT','active'),
(184,5,'Digital signature in Railway systems ensures:','File encryption and authenticity','Faster train speed','Passenger comfort','Freight tracking','File encryption and authenticity','DSC ensures secure approval.',1,'Railway AME Group B IT','active'),
(185,5,'ANUBHAV portal captures knowledge from:','Serving employees','Retired employees','Vendors','Passengers','Retired employees','ANUBHAV documents retirees experiences.',1,'Railway AME Group B IT','active'),
(186,5,'IPAS is mainly concerned with:','Personnel appraisal','Finance and payroll','Legal disputes','Medical services','Finance and payroll','IPAS manages salary and accounts.',1,'Railway AME Group B IT','active'),
(187,5,'Which module allows online leave approval in HRMS?','APAR module','Leave & Pass module','Procurement module','Medical module','Leave & Pass module','HRMS includes Leave & Pass workflow.',1,'Railway AME Group B IT','active'),
(188,5,'GeM portal promotes procurement through:','Direct negotiation only','Competitive online bidding','Manual quotation','Closed bidding','Competitive online bidding','GeM uses online competitive procurement.',1,'Railway AME Group B IT','active'),
(189,5,'SPARROW workflow includes:','Initiation, review, acceptance','Ticket booking','Vendor registration','Freight billing','Initiation, review, acceptance','APAR moves digitally through hierarchy.',1,'Railway AME Group B IT','active'),
(190,5,'RESS portal provides access to:','APAR records','Salary slips and PF','Legal cases','Procurement tenders','Salary slips and PF','RESS gives payroll info.',1,'Railway AME Group B IT','active'),
(191,5,'e-Office improves governance by:','Reducing transparency','Enhancing file tracking','Increasing paperwork','Delaying approvals','Enhancing file tracking','Files can be tracked digitally.',1,'Railway AME Group B IT','active'),
(192,5,'IREPS vendors must:','Register digitally','Submit only paper bids','Contact division physically','Use postal service','Register digitally','Vendor registration is mandatory online.',1,'Railway AME Group B IT','active'),
(193,5,'CPGRAMS helps in:','Monitoring citizen complaints','Salary disbursement','Inventory control','Signal inspection','Monitoring citizen complaints','It tracks grievance resolution.',1,'Railway AME Group B IT','active'),
(194,5,'FMM supports which integration?','Material and finance modules','Passenger and freight modules','Legal and medical modules','Signal and telecom modules','Material and finance modules','FMM integrates finance and materials.',1,'Railway AME Group B IT','active'),
(195,5,'UMID card is useful during:','Medical treatment at empanelled hospitals','Ticket booking','Freight booking','Tender participation','Medical treatment at empanelled hospitals','UMID simplifies medical verification.',1,'Railway AME Group B IT','active'),
(196,5,'HR-MIS assists management in:','Strategic manpower planning','Train control','Signal testing','Freight movement','Strategic manpower planning','HR-MIS supports workforce analysis.',1,'Railway AME Group B IT','active'),
(197,5,'Digital procurement reduces:','Transparency','Paperwork and delays','Vendor participation','Financial tracking','Paperwork and delays','Online portals speed up process.',1,'Railway AME Group B IT','active'),
(198,5,'LIMBS data helps in:','Legal strategy decisions','Salary calculation','Medical billing','Train dispatch','Legal strategy decisions','Legal monitoring improves case handling.',1,'Railway AME Group B IT','active'),
(199,5,'Integration of HRMS and IPAS ensures:','Payroll accuracy','Signal safety','Freight management','Ticket confirmation','Payroll accuracy','Employee data sync ensures correct salary.',1,'Railway AME Group B IT','active'),
(200,5,'Railway digital platforms primarily aim at:','Manual processing','Efficiency, transparency and accountability','Increasing paperwork','Reducing employee access','Efficiency, transparency and accountability','Digitalization improves governance quality.',1,'Railway AME Group B IT','active');

-- ── Sample Exams ──────────────────────────────────────────────────────────────
INSERT IGNORE INTO exams (id,title,description,topic_id,total_questions,duration_minutes,pass_percentage,negative_marking,marks_per_question,randomize_questions,is_published,created_by) VALUES
('exam-0001-0000-0000-000000000001','PC Hardware Fundamentals','Test your knowledge of computer hardware components and specifications.',1,10,15,40.00,0.25,1.00,TRUE,TRUE,'00000000-0000-0000-0000-000000000001'),
('exam-0002-0000-0000-000000000002','LAN Networking Basics','Covers hubs, switches, servers and LAN fundamentals.',2,15,20,40.00,0.25,1.00,TRUE,TRUE,'00000000-0000-0000-0000-000000000001'),
('exam-0003-0000-0000-000000000003','Internet & Email Usage','Email protocols, web browsing and internet security.',4,10,15,40.00,0.00,1.00,TRUE,TRUE,'00000000-0000-0000-0000-000000000001'),
('exam-0004-0000-0000-000000000004','Railway Digital Platforms','HRMS, IPAS, IREPS, GeM and other Railway IT systems.',5,20,25,40.00,0.25,1.00,TRUE,TRUE,'00000000-0000-0000-0000-000000000001'),
('exam-0005-0000-0000-000000000005','Full Mock Test — Railway AME IT','Complete mock test covering all topics for Railway AME Group B IT exam.',NULL,30,45,40.00,0.25,1.00,TRUE,TRUE,'00000000-0000-0000-0000-000000000001');
